version: 1
formatters:
  default:
    format: '%(asctime)s:%(name)s:%(module)s:%(funcName)s:%(lineno)d:%(levelname)s:%(message)s'
  console:
    format: '[%(asctime)s] %(levelname)-8s (%(name)s:%(funcName)s:%(lineno)d) - %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout

loggers:
  main:
    level: DEBUG
    hanlders: [console]
    propagate: true
  sample:
    level: DEBUG
    handlers: [console]
    propagate: true
  classes:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: NOTSET
  handlers: [console]